version: 2.1
jobs:
  build:
    docker:
      - image: patrickhulce/lhci-client:0.3.7
    working_directory: /home/lhci/reports
    steps:
      - checkout
      - run:
          name: lhci autorun
          command: echo $CIRCLE_BRANCH && lhci autorun --collect.staticDistDir=./www --upload.target=lhci || echo "LHCI failed!"
